{{- if and .Values.shuffle.hybrid .Values.orborus.imageManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "shuffle.orborus.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "shuffle.orborus.labels" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: image-manager
      port: {{ .Values.orborus.imageManager.port }}
      targetPort: image-manager
      protocol: TCP
      appProtocol: http
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.orborus.podLabels .Values.commonLabels) "context" .) }}
  selector: {{- include "shuffle.orborus.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 4 }}
{{- end }}
