apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shuffle.frontend.name" . }}-env
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "shuffle.frontend.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
